name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ toJSON(needs.packages.outputs.packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # Specify your Go version here

      - name: Find all packages
        id: packages
        run: |
          # Find all directories containing go.mod files (assume each sub-package has a go.mod file)
          packages=$(find . -name "go.mod" -exec dirname {} \;)
          echo "::set-output name=packages::$(echo $packages | jq -R -s 'split("\n")[:-1]')"

      - name: Build and Test Each Package
        working-directory: ${{ matrix.directory }}
        run: |
          # Build the package
          go build ./...

          # Run tests
          go test ./... -v